// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/EventService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateEventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteEventRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{3}
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateEventRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{5}
}

type ListDayEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDayEventRequest) Reset() {
	*x = ListDayEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDayEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDayEventRequest) ProtoMessage() {}

func (x *ListDayEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDayEventRequest.ProtoReflect.Descriptor instead.
func (*ListDayEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *ListDayEventRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_api_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *EventList) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventList) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *EventList) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ListDayEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventList           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDayEventResponse) Reset() {
	*x = ListDayEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDayEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDayEventResponse) ProtoMessage() {}

func (x *ListDayEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDayEventResponse.ProtoReflect.Descriptor instead.
func (*ListDayEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *ListDayEventResponse) GetEvents() []*EventList {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListWeekEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeekEventRequest) Reset() {
	*x = ListWeekEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeekEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeekEventRequest) ProtoMessage() {}

func (x *ListWeekEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeekEventRequest.ProtoReflect.Descriptor instead.
func (*ListWeekEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{9}
}

func (x *ListWeekEventRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type ListWeekEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventList           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeekEventResponse) Reset() {
	*x = ListWeekEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeekEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeekEventResponse) ProtoMessage() {}

func (x *ListWeekEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeekEventResponse.ProtoReflect.Descriptor instead.
func (*ListWeekEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{10}
}

func (x *ListWeekEventResponse) GetEvents() []*EventList {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListMonthEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonthEventRequest) Reset() {
	*x = ListMonthEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonthEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonthEventRequest) ProtoMessage() {}

func (x *ListMonthEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonthEventRequest.ProtoReflect.Descriptor instead.
func (*ListMonthEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{11}
}

func (x *ListMonthEventRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type ListMonthEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventList           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonthEventResponse) Reset() {
	*x = ListMonthEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonthEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonthEventResponse) ProtoMessage() {}

func (x *ListMonthEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonthEventResponse.ProtoReflect.Descriptor instead.
func (*ListMonthEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{12}
}

func (x *ListMonthEventResponse) GetEvents() []*EventList {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_EventService_proto protoreflect.FileDescriptor

const file_api_EventService_proto_rawDesc = "" +
	"\n" +
	"\x16api/EventService.proto\x12\x05event\"\x84\x01\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\"%\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x15\n" +
	"\x13DeleteEventResponse\"\x94\x01\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tstartDate\x18\x04 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x05 \x01(\tR\aendDate\"\x15\n" +
	"\x13UpdateEventResponse\"'\n" +
	"\x13ListDayEventRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\"\x8b\x01\n" +
	"\tEventList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tstartDate\x18\x04 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x05 \x01(\tR\aendDate\"@\n" +
	"\x14ListDayEventResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventListR\x06events\"(\n" +
	"\x14ListWeekEventRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\"A\n" +
	"\x15ListWeekEventResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventListR\x06events\")\n" +
	"\x15ListMonthEventRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\"B\n" +
	"\x16ListMonthEventResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventListR\x06events2\xb5\x03\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponse\x12D\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x12B\n" +
	"\aListDay\x12\x1a.event.ListDayEventRequest\x1a\x1b.event.ListDayEventResponse\x12E\n" +
	"\bListWeek\x12\x1b.event.ListWeekEventRequest\x1a\x1c.event.ListWeekEventResponse\x12H\n" +
	"\tListMonth\x12\x1c.event.ListMonthEventRequest\x1a\x1d.event.ListMonthEventResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_api_EventService_proto_rawDescOnce sync.Once
	file_api_EventService_proto_rawDescData []byte
)

func file_api_EventService_proto_rawDescGZIP() []byte {
	file_api_EventService_proto_rawDescOnce.Do(func() {
		file_api_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)))
	})
	return file_api_EventService_proto_rawDescData
}

var file_api_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_EventService_proto_goTypes = []any{
	(*CreateEventRequest)(nil),     // 0: event.CreateEventRequest
	(*CreateEventResponse)(nil),    // 1: event.CreateEventResponse
	(*DeleteEventRequest)(nil),     // 2: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),    // 3: event.DeleteEventResponse
	(*UpdateEventRequest)(nil),     // 4: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),    // 5: event.UpdateEventResponse
	(*ListDayEventRequest)(nil),    // 6: event.ListDayEventRequest
	(*EventList)(nil),              // 7: event.EventList
	(*ListDayEventResponse)(nil),   // 8: event.ListDayEventResponse
	(*ListWeekEventRequest)(nil),   // 9: event.ListWeekEventRequest
	(*ListWeekEventResponse)(nil),  // 10: event.ListWeekEventResponse
	(*ListMonthEventRequest)(nil),  // 11: event.ListMonthEventRequest
	(*ListMonthEventResponse)(nil), // 12: event.ListMonthEventResponse
}
var file_api_EventService_proto_depIdxs = []int32{
	7,  // 0: event.ListDayEventResponse.events:type_name -> event.EventList
	7,  // 1: event.ListWeekEventResponse.events:type_name -> event.EventList
	7,  // 2: event.ListMonthEventResponse.events:type_name -> event.EventList
	0,  // 3: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	2,  // 4: event.EventService.DeleteEvent:input_type -> event.DeleteEventRequest
	4,  // 5: event.EventService.UpdateEvent:input_type -> event.UpdateEventRequest
	6,  // 6: event.EventService.ListDay:input_type -> event.ListDayEventRequest
	9,  // 7: event.EventService.ListWeek:input_type -> event.ListWeekEventRequest
	11, // 8: event.EventService.ListMonth:input_type -> event.ListMonthEventRequest
	1,  // 9: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	3,  // 10: event.EventService.DeleteEvent:output_type -> event.DeleteEventResponse
	5,  // 11: event.EventService.UpdateEvent:output_type -> event.UpdateEventResponse
	8,  // 12: event.EventService.ListDay:output_type -> event.ListDayEventResponse
	10, // 13: event.EventService.ListWeek:output_type -> event.ListWeekEventResponse
	12, // 14: event.EventService.ListMonth:output_type -> event.ListMonthEventResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_EventService_proto_init() }
func file_api_EventService_proto_init() {
	if File_api_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_EventService_proto_goTypes,
		DependencyIndexes: file_api_EventService_proto_depIdxs,
		MessageInfos:      file_api_EventService_proto_msgTypes,
	}.Build()
	File_api_EventService_proto = out.File
	file_api_EventService_proto_goTypes = nil
	file_api_EventService_proto_depIdxs = nil
}
